### PR TITLE
Improve formatting of warnings

### LINKED ISSUE #7: Printed warning looks torn apart.
When there is no browser set via `GOCEPT_WEBDRIVER_BROWSER,` a warning gets issued.

The warning in the source code is indented without the usage of dedent or similar.

Thus, the warning in the console looks torn apart, see screenshot.

Screenshot from 2019-11-19 09-15-13

### PR DESCRIPTION
**Pull request by jugmac00**
... when environment variables are not set to a valid value.

This fixes #7

### CODE REVIEW

**Comment by jugmac00** [comment]
The failure seems unrelated 

```
E       ImportError: cannot import name 'ComponentLookupError' from 'zope.component.interfaces' (/home/runner/work/gocept.selenium/gocept.selenium/.tox/py37-grok-ff-headless/lib/python3.7/site-packages/zope/component/interfaces.py)
```

**Comment by icemac** [comment]
The tests fail because `grokcore.rest` is not yet compatible with `zope.component >= 5`.
The failing lint test looks strange indeed. (cc: @sallner)

**Comment by icemac** [comment]
Please rebase on current master. It should be fixed by now.

**Comment by icemac** [comment]
Sorry, I touched the same code locally and I am going to create a separate PR as my changes go even further.

**Comment by jugmac00** [comment]
@icemac I am not sure what to do now - can you clarify? Thank you!

**Comment by icemac** [comment]
@jugmac00 Sorry for being vague: I meant #30 supersedes your PR.

**Pull request closed without merging**
